language: node_js
node_js:
  - "6"

branches:
  only:
    - master

cache:
  directories:
    - node_modules

script:
  - npm run build.prod

deploy:
  provider: pages
  skip_cleanup: true
  github_token: 853d8d42e45bc46fbbcd455af9dc16316d4759c6
  local_dir: dist
  on:
    branch: master
