language: node_js
node_js:
  - "8"

branches:
  only:
    - master

cache:
  directories:
    - node_modules

before_script:
  - git config --global user.email "ledicjp@gmail.com"
  - git config --global user.name "Josip Ledic"

script:
  - npm run build.prod

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist
  on:
    branch: master
